baseURL = '/'
languageCode = 'en-us'
defaultContentLanguage = 'en'

title = 'Sugar ODM Documentation'
theme = 'hugo-theme-learn'
defaultContentLanguageInSubdir = true
uglyurls = true

# For search functionality
[outputs]
  home = [ 'HTML', 'RSS', 'JSON']

[params]
  description = 'Documentation for Sugar ODM'
  author = 'Paul Severance'
  themeVariant = 'purple'
